version: '3.3'
services:
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: 'traffic'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      - "3008:3306"
    expose:
      - '3008'
    volumes:
      - traffic-db:/var/lib/mysql

volumes:
  traffic-db: