version: '3.3'
services:
  db-port-3011:
    image: mysql:8.0.25
    restart: always
    container_name: mysqlPort3011
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'traffic'
    ports:
      - "3011:3306"
    expose:
      - '3011'
    volumes:
      - traffic-db-3011:/var/lib/mysql

volumes:
  traffic-db-3011: