version: '3.3'
services:
  db-port-3014:
    image: mysql:8.0.25
    restart: always
    container_name: mysqlPort3014
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'traffic'
    ports:
      - "3014:3306"
    expose:
      - '3014'
    volumes:
      - traffic-db-3014:/var/lib/mysql

volumes:
  traffic-db-3014: