version: '3.3'
services:
  db-port-3013:
    image: mysql:8.0.25
    restart: always
    container_name: mysqlPort3013
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'traffic-1'
    command: mysqld --sql_mode=""
    ports:
      - "3013:3306"
    expose:
      - '3013'
    volumes:
      - traffic-db-3013:/var/lib/mysql

volumes:
  traffic-db-3013: